
### what is the total revenue generated by male vs.female customers?

SELECT gender, SUM(purchase_amount_usd) as revenue
FROM yeni_tablo_adi
GROUP BY gender;

## which customers used a discount but still spent more than the average amount?


SELECT customer_id, purchase_amount_usd
FROM yeni_tablo_adi
WHERE discount_applied='Yes' and purchase_amount_usd >= (select AVG(purchase_amount_usd) FROM yeni_tablo_adi);
 
## Which are the top 5 product with the highest average review rating?

SELECT item_purchased, AVG(review_rating) as "AverageRating"
from yeni_tablo_adi
group by item_purchased
order by avg(review_rating) desc
limit 5;


## Compare the average purchase amounts between standard and express shipping.

SELECT shipping_type, AVG(purchase_amount_usd)
FROM yeni_tablo_adi
WHERE shipping_type in ('Standard','Express')
group by shipping_type;

## do subscribed customers spend more? compare average spend and total revenue between subscrıbers and non-sub.

SELECT subscription_status,
count(customer_id) as total_customers,
AVG(purchase_amount_usd) as avg,
SUM(purchase_amount_usd) as sum
FROM yeni_tablo_adi
GROUP BY subscription_status
order by avg , sum desc;

## Which 5 products have the highest percentage of purchases with discounts applied?

SELECT 
    item_purchased,
    ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*) * 100, 2) AS discount_rate
FROM yeni_tablo_adi
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


## segment customers into new, returnıng, and loyal based on their total number of previous purchased and show the count of each segment

WITH customer_type AS (
    SELECT 
        customer_id, 
        previous_purchases,
        CASE 
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM yeni_tablo_adi
)

SELECT customer_segment, COUNT(*) as sumCustomer
FROM customer_type
GROUP BY customer_segment;

## WHAT are the top 3 most purchased product within each category
WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders, 
        ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM yeni_tablo_adi 
    GROUP BY category, item_purchased
)
SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;

## Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
count(customer_id) as repeat_buyers
from yeni_tablo_adi
where previous_purchases > 5
group by subscription_status;

## What is the revenue contribution of each age group?

SELECT age_group,
SUM(purchase_amount_usd) as total_revenue
FROM yeni_tablo_adi
group by age_group
order by total_revenue desc
;









